include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    one_member_abstracts: false
    sort_pub_dependencies: false
    avoid_positional_boolean_parameters: false
    avoid_catches_without_on_clauses: false
    unintended_html_in_doc_comment: false