name: example
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  pars3r: 
    path: ../
  
  firebase_core: ^3.10.0
  firebase_remote_config: ^5.3.0

  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true