name: pars3r
description: A Dart library for parsing `String` values into various object types with type safety and ease of use.
version: 0.1.0+1
homepage: https://github.com/mysCod3r/pars3r
repository: https://github.com/mysCod3r/pars3r
issue_tracker: https://github.com/mysCod3r/pars3r/issues
topics: 
  - parsing
  - serialization
  - model
  - dart
  - flutter
  - utilities
  - type-safety


environment:
  sdk: ^3.5.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
